version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: chat-rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

    restart: always


  redis:
    image: redis:7-alpine
    container_name: chat-redis

    ports:
      - "6379:6379"

    restart: always